practicos/25 - 59070 - Ladina, Maia Agostina/TP1/index.css
practicos/25 - 59070 - Ladina, Maia Agostina/TP1/index.html
practicos/25 - 59070 - Ladina, Maia Agostina/TP1/index.jsx

Trabajo Practico 1

---

practicos/17 - 59068 - Gonzalez, Silvina Mariela/TP1/index.css
practicos/17 - 59068 - Gonzalez, Silvina Mariela/TP1/index.html
practicos/17 - 59068 - Gonzalez, Silvina Mariela/TP1/index.jsx

Trabajo Práctico No1

---

practicos/36 - 59054 - Rahman Rintoul, Ramiro/.vscode/settings.json
practicos/36 - 59054 - Rahman Rintoul, Ramiro/TP1/index.css
practicos/36 - 59054 - Rahman Rintoul, Ramiro/TP1/index.html
practicos/36 - 59054 - Rahman Rintoul, Ramiro/TP1/index.jsx

**Alumno**: Ramiro Rahman Rintoul
**Legajo**: 59054
_**TUP-C5**_

Trabajo Práctico N°1

---

practicos/44 - 58845 - Terrera, Augusto Dante/TP1/index.css
practicos/44 - 58845 - Terrera, Augusto Dante/TP1/index.html
practicos/44 - 58845 - Terrera, Augusto Dante/TP1/index.jsx

Trabajo Practico N1

---

practicos/22 - 58761 - Juarez, Lautaro Andres/TP1/index.css
practicos/22 - 58761 - Juarez, Lautaro Andres/TP1/index.html
practicos/22 - 58761 - Juarez, Lautaro Andres/TP1/index.jsx

tp1 Juarez Lautaro

---

practicos/24 - 58721 - Juncos, Gonzalo Sebastian/TP1/index.css
practicos/24 - 58721 - Juncos, Gonzalo Sebastian/TP1/index.html
practicos/24 - 58721 - Juncos, Gonzalo Sebastian/TP1/index.jsx

Juncos gonzalo 58721

---

practicos/07 - 58895 - Flores Gonzalez, Tomas/TP1/index.css
practicos/07 - 58895 - Flores Gonzalez, Tomas/TP1/index.html
practicos/07 - 58895 - Flores Gonzalez, Tomas/TP1/index.jsx

Trabajo finalizado

---

practicos/53 - 59909 - Wierna, Belén/.vscode/launch.json
practicos/53 - 59909 - Wierna, Belén/TP1/index.css
practicos/53 - 59909 - Wierna, Belén/TP1/index.html
practicos/53 - 59909 - Wierna, Belén/TP1/index.jsx

TP 1 Wierna, Belen

---

practicos/03 - 58773 - Elli Salazar, Gerónimo/TP1/index.css
practicos/03 - 58773 - Elli Salazar, Gerónimo/TP1/index.html
practicos/03 - 58773 - Elli Salazar, Gerónimo/TP1/index.jsx

Disculpe profe, este practico lo subi desde la pc de mi compañera por que la mia no funcionaba, soy de la comision 5 Elli Salazar Geronimo

tp1 elli geronimo agenda

---

practicos/28 - 58727 - Lazarte, Lucas/TP1/index.css
practicos/28 - 58727 - Lazarte, Lucas/TP1/index.html
practicos/28 - 58727 - Lazarte, Lucas/TP1/index.jsx

TP1 Lazarte Lucas

---

practicos/30 - 58724 - Lopez Garcia, Marcos Juli/TP1/index.css
practicos/30 - 58724 - Lopez Garcia, Marcos Juli/TP1/index.html
practicos/30 - 58724 - Lopez Garcia, Marcos Juli/TP1/index.jsx

Profesor aca le dejo el tp terminado :).
Atte: Lopez Garcia Julian, disculpe la demora.

TP1 Terminado 58724

---

practicos/07 - 58895 - Flores Gonzalez, Tomas/TP2/index.html

Tra2flores

---

practicos/44 - 58845 - Terrera, Augusto Dante/TP2/index.html

Trabajo Practico 2

---

practicos/28 - 58727 - Lazarte, Lucas/TP2/index.html

TP2-Lazarte Lucas

---

practicos/30 - 58724 - Lopez Garcia, Marcos Juli/TP2/index.html

Lopez Garcia Julian - 58724. TP2 Realizado

TP2 Realizado Lopez Julian

---

practicos/29 - 59152 - Lopez Chipoloni, Agustin/TP2/index.html

TP2 Agustin

---

practicos/32 - 58729 - Lovey, Mathias Exequiel/TP2/index.html

Trabajo Practico N°2

---

practicos/18 - 58786 - Gutierrez, Augusto Pedro/TP2/index.html
practicos/18 - 58786 - Gutierrez, Augusto Pedro/TP2/scripts/app.js
practicos/18 - 58786 - Gutierrez, Augusto Pedro/TP2/scripts/main.js
practicos/18 - 58786 - Gutierrez, Augusto Pedro/TP2/style/style.css

Hola Profesor hago entrega del TP2. 
Este practicos tiene cambios en el orden en como se acomodaron las etiquetas html, creo carpetas para separar mucho mejor los archivos logicos, de estilos y de estructura. Tambien cambie los scripts antiguos de React.js a los nuevos scripts de React.js 18. 
Esta agenda no manipula el array original de objeto.

Trabajo Practico Numero 2 Terminado

---

practicos/36 - 59054 - Rahman Rintoul, Ramiro/TP3/Index.html
practicos/36 - 59054 - Rahman Rintoul, Ramiro/TP3/almacen.svg

Este proyecto es una aplicación web para el control de inventario de productos utilizando React. Permite añadir, editar, incrementar y eliminar productos de una lista, así como almacenar información de los productos agregados en el `localStorage`.
1. **Añadir Producto**:
- Ingrese el nombre del producto y el código EAN en los campos de entrada correspondientes.
- Haga clic en el botón de agregar (botón azul con el símbolo "+").
- Si el producto ya existe (mismo código EAN), se incrementará la cantidad en 1.
- Si es un nuevo producto, se añadirá a la lista.
- El nuevo producto también se guardará en `localStorage` bajo la clave "ProductoAgregado".
2. **Editar Producto**:
- Haga clic en el ícono de lápiz para editar un producto existente.
- Modifique el nombre, el código EAN y la cantidad …

Parcial N°1 Laboratorio | TP3 - 59054

---

practicos/43 - 55870 - Stemberger, Emiliano/TP3/index.html

TP3-{EmilianoStemberger}

---

practicos/18 - 58786 - Gutierrez, Augusto Pedro/TP3/css/style.css
practicos/18 - 58786 - Gutierrez, Augusto Pedro/TP3/index.html
practicos/18 - 58786 - Gutierrez, Augusto Pedro/TP3/scripts/app.js

**Trabajo Practico Numero 3 Finalizado**
Este proyecto inicia con un array de objetos creado previamente el cual se mostrara en el DOM de forma ordenada Alfabéticamente (A - Z) . Al lado del titulo contara con un botón que permitirá crear nuevos productos los cuales cuenta con las siguientes validaciones:
- No permitirá que se cree un producto vacío.
- No permitirá agregar un producto con el mismo código EAN de otro producto.
- No permitirá agregar un producto con cantidades negativas.
AL crear un nuevo producto, este se posicionara en la lista en orden alfabético el cual puede ser eliminado y modificado. Al modificar el producto contara con las mismas validaciones que tiene al crear el mismo, logrando una lógica solida para evitar errores de código repetido, cantidades negativas, etc. …

TP3 Finalizado Augusto Gutierrez 58786

---

practicos/13 - 59135 - Gomez, Facundo Matias/TP3/index.htm

tp3 facundo gomez matias

---

practicos/30 - 58724 - Lopez Garcia, Marcos Juli/TP3/index.html

Listo profe, tuve poco tiempo de hacerlo debido a la pesada organizacion de mis dias. Espero pueda entender profe. Gracias

TP3 JULIAN LOPEZ

---

practicos/29 - 59152 - Lopez Chipoloni, Agustin/TP3/index.css
practicos/29 - 59152 - Lopez Chipoloni, Agustin/TP3/index.html

Corrección

---

practicos/53 - 59909 - Wierna, Belén/TP3/index.html

Correccion

---

practicos/32 - 58729 - Lovey, Mathias Exequiel/TP3/index.css
practicos/32 - 58729 - Lovey, Mathias Exequiel/TP3/index.html
practicos/32 - 58729 - Lovey, Mathias Exequiel/TP3/index.jsx

Corrección de TP3

---

practicos/33 - 59071 - Medina, Daiana Micaela/TP3/index.jsx

Correción TP3

---

practicos/44 - 58845 - Terrera, Augusto Dante/TP3/index.html

Agrego la funcionalidad de poder editar varios productos a la vez

TP N°3 Corrección

---

practicos/30 - 58724 - Lopez Garcia, Marcos Juli/TP3/index.html

AQUI ENTREGO LA CORRECCION PROFE CON TODOS LOS REQUISITOS AÑADIDOS/CUMPLIDOS

Correccion TP3 57824 LOPEZ GARCIA JULIAN

---

practicos/18 - 58786 - Gutierrez, Augusto Pedro/TP3/css/style.css
practicos/18 - 58786 - Gutierrez, Augusto Pedro/TP3/index.html
practicos/18 - 58786 - Gutierrez, Augusto Pedro/TP3/scripts/app.js

**Trabajo Practico Numero 3 Corregido y Terminado** 
En este pull request corrige los errores de estilos, ahora el diseño es responsivo a vista desktop y mobile. 
Este nuevo cambio trae la funcionalidad de hacer click en cada tarjeta y aumentar la cantidad de cada producto.
Siempre que se cree o se edite cada tarjeta pasara por una serie de validaciones y siempre se mostraran en orden alfabético (A-Z).  Tambien se añadió una notificación push que indica si paso o no las validaciones con mensajes de error.
Augusto Gutierrez
Legajo: 58.786

Estilo responsivo terminado, Logica terminada

---

practicos/49 - 58899 - Villagra, Juan Gabriel/TP3/index.html

1°Parcial / TP-3

---

practicos/18 - 58786 - Gutierrez, Augusto Pedro/TP4/estilo.css
practicos/18 - 58786 - Gutierrez, Augusto Pedro/TP4/index.html
practicos/18 - 58786 - Gutierrez, Augusto Pedro/TP4/main.jsx
practicos/18 - 58786 - Gutierrez, Augusto Pedro/TP4/style.css

**Trabajo Practico Numero 4 Terminado.** 
En este proyecto agrego también alertas del clima de cada cuidad.
Augusto Gutierrez
58786

Trabajo Practico 4 Terminado

---

practicos/07 - 58895 - Flores Gonzalez, Tomas/TP5/app.js

Tp5-FloresTomas

---

practicos/29 - 59152 - Lopez Chipoloni, Agustin/TP5/app.js
practicos/29 - 59152 - Lopez Chipoloni, Agustin/TP5/persona.test.js

TP5-Chipoloni

---

practicos/53 - 59909 - Wierna, Belén/TP4/estilo.css
practicos/53 - 59909 - Wierna, Belén/TP4/icon.Mapping.js
practicos/53 - 59909 - Wierna, Belén/TP4/main.jsx

tp4- Wierna

---

practicos/15 - 59488 - Gonzalez, Mariano Emanuel/TP5/app.js
practicos/15 - 59488 - Gonzalez, Mariano Emanuel/TP5/package-lock.json

Tp5 Mariano

---

practicos/15 - 59488 - Gonzalez, Mariano Emanuel/TP6/package.json
practicos/15 - 59488 - Gonzalez, Mariano Emanuel/TP6/public/estilo.css
practicos/15 - 59488 - Gonzalez, Mariano Emanuel/TP6/public/index.html
practicos/15 - 59488 - Gonzalez, Mariano Emanuel/TP6/public/main.jsx
practicos/15 - 59488 - Gonzalez, Mariano Emanuel/TP6/servidor.js

tp6 Mariano

---

practicos/33 - 59071 - Medina, Daiana Micaela/TP6/package-lock.json
practicos/33 - 59071 - Medina, Daiana Micaela/TP6/public/estilo.css
practicos/33 - 59071 - Medina, Daiana Micaela/TP6/public/main.jsx
practicos/33 - 59071 - Medina, Daiana Micaela/TP6/servidor.js

TP6 - Medina Micaela

---

practicos/53 - 59909 - Wierna, Belén/TP6/.vscode/settings.json
practicos/53 - 59909 - Wierna, Belén/TP6/package.json
practicos/53 - 59909 - Wierna, Belén/TP6/public/index.html
practicos/53 - 59909 - Wierna, Belén/TP6/public/main.jsx
practicos/53 - 59909 - Wierna, Belén/TP6/servidor.js

tp6-Wierna

---

practicos/30 - 58724 - Lopez Garcia, Marcos Juli/TP5/app.js
practicos/30 - 58724 - Lopez Garcia, Marcos Juli/TP6/package.json
practicos/30 - 58724 - Lopez Garcia, Marcos Juli/TP6/public/index.html
practicos/30 - 58724 - Lopez Garcia, Marcos Juli/TP6/public/main.jsx
practicos/30 - 58724 - Lopez Garcia, Marcos Juli/TP6/servidor.js

TP6 - LOPEZ JULIAN

---

practicos/21 - 58736 - Juarez Hindi, Lucas David/TP6/public/estilo.css
practicos/21 - 58736 - Juarez Hindi, Lucas David/TP6/public/index.html
practicos/21 - 58736 - Juarez Hindi, Lucas David/TP6/public/main.jsx
practicos/21 - 58736 - Juarez Hindi, Lucas David/TP6/servidor.js

Commit TP6

---

practicos/32 - 58729 - Lovey, Mathias Exequiel/TP6/package.json
practicos/32 - 58729 - Lovey, Mathias Exequiel/TP6/public/index.html
practicos/32 - 58729 - Lovey, Mathias Exequiel/TP6/public/main.jsx
practicos/32 - 58729 - Lovey, Mathias Exequiel/TP6/servidor.js

TP6 Mathias Lovey

---

practicos/07 - 58895 - Flores Gonzalez, Tomas/TP6/controllers/usuario.js
practicos/07 - 58895 - Flores Gonzalez, Tomas/TP6/package.json
practicos/07 - 58895 - Flores Gonzalez, Tomas/TP6/public/estilo.css
practicos/07 - 58895 - Flores Gonzalez, Tomas/TP6/public/main.jsx
practicos/07 - 58895 - Flores Gonzalez, Tomas/TP6/servidor.js

Trabajo realizado con los los objetivos dichos en el git

TP6-FloresTomas

---

practicos/29 - 59152 - Lopez Chipoloni, Agustin/TP6/public/estilo.css
practicos/29 - 59152 - Lopez Chipoloni, Agustin/TP6/public/index.html
practicos/29 - 59152 - Lopez Chipoloni, Agustin/TP6/public/main.jsx
practicos/29 - 59152 - Lopez Chipoloni, Agustin/TP6/servidor.js

Tp6chipoloni

---

practicos/39 - 58686 - Rodriguez, Gustavo/TP6/public/index.html
practicos/39 - 58686 - Rodriguez, Gustavo/TP6/public/main.jsx
practicos/39 - 58686 - Rodriguez, Gustavo/TP6/servidor.js

profe me demore en subirlo porque tenia muchos errores y recien hoy pude solucionar el error

trabajoPractico Numero 6

---

practicos/39 - 58686 - Rodriguez, Gustavo/TP6/public/estilo.css
practicos/39 - 58686 - Rodriguez, Gustavo/TP6/public/index.html
practicos/39 - 58686 - Rodriguez, Gustavo/TP6/public/main.jsx
practicos/39 - 58686 - Rodriguez, Gustavo/TP6/servidor.js

Buenos Noches  Profesor. El programa ya esta completamente funcional con los requirimientos que usted pidio. Espero que este bien

tp6-GustavoRodriguez

---

practicos/01 - 55681 - Bustos, Mauricio Benjamin/TP5/app.js

tp 5 Nunca se envio profe :(

---

practicos/21 - 58736 - Juarez Hindi, Lucas David/TP3/index.html
practicos/21 - 58736 - Juarez Hindi, Lucas David/TP3/style.css

El problema por el cual no permitía agregar un producto cuando se estaba editando, era en la const agregarProduct (ahora llamada const agregar), en la que había un if que no lo permitía, ahora esta solucionado El diseño también fue mejorado

TP 3 Corregido

---

practicos/21 - 58736 - Juarez Hindi, Lucas David/TP3/index.html
practicos/21 - 58736 - Juarez Hindi, Lucas David/TP3/style.css

El problema por el cual no permitía agregar un producto cuando se estaba editando, era en la const agregarProduct (ahora llamada const agregar), en la que había un if que no lo permitía, ahora esta solucionado El diseño también fue mejorado

TP N° 3 Corregido

---

practicos/21 - 58736 - Juarez Hindi, Lucas David/TP3/index.html
practicos/21 - 58736 - Juarez Hindi, Lucas David/TP3/style.css

El problema de no poder agregar un nuevo producto mientras se edita otro fue solucionado, también el diseño es idéntico al original

TP N°3 Corregido
